ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

# KOTH-EU
La base a était release pour les cause suivante : L'ancien designer UI nous ments, donne la base a des personnes qui se font passer pour le déveloper, j'ai travailler + de 2 / 3 mois sur la base, cet 3 mois ont était difficile pour moi, a cette époque je ne savais réelement pas quoi faire avec ce gros projet, j'ai appris + avec ce projet

Donc merci de ne pas critiquez le code ! OUI le code est moches des boucles inutile et autres !

# Support me on Paypal :

image::https://lh3.googleusercontent.com/proxy/0rpHNjYu5yDk7TqtKFcian7aMtsCDH_utUnhstTEZheez_tgbq19ddjfoj_xVUh0VEgSGM23CtsvFjWGrF6bAATtoiHyiNMX16cKgwbmVRkBtKCKtNjjLy1UIBeJugZP[Support me on paypal,link="https://streamelements.com/loze_kylian/tip"]

Merci au donateur !

=== Help / Information

WARNING: Le code est vraiment déguelasse à cette époque je ne savais rien faire, je n'avais jamais fait un aussi gros projet, donc je me suis éparpiller un peu partout en faisant des boucles très moches.

TIP: Pensez bien a mettre le SQL pour que le server marche !

NOTE: Je ne donnerais aucun support !

== Credits

.GameMode
[horizontal]
Véhicule:: DMZ
Mapper:: Nampac
Developer:: Kylian
