_type = "vehicule"  

local p = ".PNG"

ImageWeapons = {
    ["1"] = "WEAPON_COMPACTRIFLE"..p,
    ["2"] = "WEAPON_ASSAULTRIFLE"..p,
    ["3"] = "WEAPON_CARBINERIFLE"..p,
    ["4"] = "WEAPON_ADVANCEDRIFLE"..p,
    ["5"] = "WEAPON_BULLPUPRIFLE"..p,
    ["6"] = "WEAPON_SPECIALCARBINE"..p,
    ["7"] = "WEAPON_ASSAULTRIFLE_MK2"..p,
    ["8"] = "WEAPON_CARBINERIFLE_MK2"..p,
    ["9"] = "WEAPON_SPECIALCARBINE_MK2"..p,
    ["10"] = "WEAPON_SNSPISTOL"..p,
    ["11"] = "WEAPON_FLAREGUN"..p,
    ["12"] = "WEAPON_PISTOL"..p,
    ["13"] = "WEAPON_COMBATPISTOL"..p,
    ["14"] = "WEAPON_SNSPISTOL_MK2"..p,
    ["15"] = "WEAPON_DBSHOTGUN"..p,
    ["16"] = "WEAPON_HEAVYPISTOL"..p,
    ["17"] = "WEAPON_PISTOL50"..p,
    ["18"] = "WEAPON_PISTOL_MK2"..p,
    ["19"] = "WEAPON_APPISTOL"..p,
    ["20"] = "WEAPON_REVOLVER"..p,
    ["21"] = "WEAPON_REVOLVER_MK2"..p,
    ["22"] = "WEAPON_GRENADE"..p,
    ["23"] = "WEAPON_BZGAS"..p,
    ["24"] = "WEAPON_COMPACTLAUNCHER"..p,
    ["25"] = "GADGET_PARACHUTE"..p,
    ["26"] = "WEAPON_PUMPSHOTGUN"..p,
    ["27"] = "WEAPON_BULLPUPSHOTGUN"..p,
    ["28"] = "WEAPON_AUTOSHOTGUN"..p,
    ["29"] = "WEAPON_HEAVYSHOTGUN"..p,
    ["30"] = "WEAPON_PUMPSHOTGUN_MK2"..p,
    ["31"] = "WEAPON_ASSAULTSHOTGUN"..p,
    ["31"] = "WEAPON_MINISMG"..p,
    ["32"] = "WEAPON_SMG"..p,
    ["33"] = "WEAPON_MICROSMG"..p,
    ["34"] = "WEAPON_MACHINEPISTOL"..p,
    ["35"] = "WEAPON_COMBATPDW"..p,
    ["36"] = "WEAPON_CARBINERIFLE_MK2"..p,
    ["37"] = "WEAPON_ASSAULTSMG"..p,
    ["38"] = "repairkit",
    ["39"] = "WEAPON_RPG"..p,
    ["40"] = "WEAPON_HOMINGLAUNCHER"..p,
    ["41"] = "WEAPON_GRENADELAUNCHER"..p,
    ["42"] = "WEAPON_GRENADELAUNCHER_SMOKE"..p,
    ["43"] = "WEAPON_MG"..p,
    ["44"] = "WEAPON_GUSENBERG"..p,
    ["45"] = "WEAPON_COMBATMG"..p,
    ["46"] = "WEAPON_COMBATMG_MK2"..p,
    ["47"] = "WEAPON_MARKSMANRIFLE"..p,
    ["48"] = "WEAPON_MARKSMANRIFLE_MK2"..p,
    ["49"] = "WEAPON_SNIPERRIFLE"..p,
    ["50"] = "WEAPON_MUSKET"..p,
    ["51"] = "WEAPON_HEAVYSNIPER"..p,
    ["52"] = "WEAPON_DOUBLEACTION"..p,
    --["5748568104"] = "weapon_heavysniper",
    --["5748568105"] = "weapon_heavysniper",
}

Citizen.CreateThread(function()
    local num = 1
_items = {
    -- Infrantery
        {id = "WEAPON_COMPACTRIFLE",name = "Ak-U", desc = "", lvl = "1", thumb = "WEAPON_COMPACTRIFLE.PNG", rent = "free", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_ASSAULTRIFLE',name = "Ak-47", desc = "", lvl = "2", thumb = "WEAPON_ASSAULTRIFLE.PNG", rent = "100", buy = "75000", own = "1000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_CARBINERIFLE',name = "M4", desc = "", lvl = "10", thumb = "WEAPON_CARABINERIFLE.PNG", rent = "250", buy = "85000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_ADVANCEDRIFLE',name = "Advanced", desc = "", lvl = "23", thumb = "WEAPON_ADVANCEDRIFLE.PNG", rent = "250", buy = "75000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_BULLPUPRIFLE',name = "BullPup", desc = "", lvl = "38", thumb = "WEAPON_BULLPUPRIFLE.PNG", rent = "250", buy = "100500", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_SPECIALCARBINE',name = "G36", desc = "", lvl = "45", thumb = "WEAPON_SPECIALCARBINE.PNG", rent = "300", buy = "130000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_ASSAULTRIFLE_MK2',name = "Ak Mk2", desc = "", lvl = "61", thumb = "WEAPON_ASSAULTRIFLE_MK2.PNG", rent = "350", buy = "143500", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_BULLPUPRIFLE',name = "BullPup Mk2", desc = "", lvl = "67", thumb = "WEAPON_BULLPUPRIFLE_MK2.PNG", rent = "350", buy = "145000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_CARBINERIFLE_MK2',name = "M4 Mk2", desc = "", lvl = "71", thumb = "WEAPON_CARBINERIFLE_MK2.PNG", rent = "350", buy = "167000", class = "infantry", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_SPECIALCARBINE_MK2',name = "G36 Mk2", desc = "", lvl = "81", thumb = "WEAPON_SPECIALCARBINE_MK2.PNG", rent = "400", buy = "180000", class = "infantry", cat = "weapon", wrap = "primary"},
        
        {id = 'WEAPON_SNSPISTOL', name = "SnS Pistol", desc = "", lvl = "1", thumb = "WEAPON_SNSPISTOL.PNG", rent = "free", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_FLAREGUN', name = "FlareGun", desc = "", lvl = "3", thumb = "WEAPON_FLAREGUN.PNG", rent = "50", buy = "2500", own = "1000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL', name = "Pistol", desc = "", lvl = "5", thumb = "WEAPON_PISTOL.PNG", rent = "100", buy = "20000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPISTOL', name = "Combat Pistol", desc = "", lvl = "6", thumb = "WEAPON_COMBATPISTOL.PNG", rent = "150", buy = "25000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SNSPISTOL_MK2', name = "SnS Pistol Mk2", desc = "", lvl = "11", thumb = "WEAPON_SNSPISTOL_MK2.PNG", rent = "125", buy = "32500", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_DBSHOTGUN', name = "Double Barrel Shotgun", desc = "", lvl = "14", thumb = "WEAPON_DBSHOTGUN.PNG", rent = "200", buy = "55000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_HEAVYPISTOL', name = "Heavy Pistol", desc = "", lvl = "20", thumb = "WEAPON_HEAVYPISTOL.PNG", rent = "200", buy = "58000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL50', name = "Pistol 50", desc = "", lvl = "29", thumb = "WEAPON_PISTOL50.PNG", rent = "250", buy = "61000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_APPISTOL', name = "Appistol", desc = "", lvl = "53", thumb = "WEAPON_APPISTOL.PNG", rent = "250", buy = "85000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_DOUBLEACTION', name = "Double Action", desc = "", lvl = "62", thumb = "WEAPON_DOUBLEACTION.PNG", rent = "275", buy = "90000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_REVOLVER', name = "Revolver", desc = "", lvl = "72", thumb = "WEAPON_REVOLVER.PNG", rent = "250", buy = "100000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_REVOLVER_MK2', name = "Revolver Mk2", desc = "", lvl = "97", thumb = "WEAPON_REVOLVER_MK2.PNG", rent = "300", buy = "120000", class = "infantry", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_GRENADE',name = "Grenade", desc = "", lvl = "1", thumb = "WEAPON_GRENADE.PNG", rent = "175", class = "infantry", cat = "weapon", wrap = "throwable"},
        {id = 'WEAPON_GRENADELAUNCHER_SMOKE',name = "Grenade Gas", desc = "", lvl = "15", thumb = "WEAPON_GRENADELAUNCHER_SMOKE.PNG", rent = "400", buy = "240000", class = "infantry", cat = "weapon", wrap = "throwable"},
        {id = 'WEAPON_COMPACTLAUNCHER',name = "Compact Launcher", desc = "", lvl = "35", thumb = "WEAPON_COMPACTLAUNCHER.PNG", rent = "500", buy = "285000", class = "infantry", cat = "weapon", wrap = "throwable"},
        {id = 'GADGET_PARACHUTE',name = "Parachute", desc = "", lvl = "60", thumb = "WEAPON_PARACHUTE.PNG", rent = "300", buy = "75000", class = "infantry", cat = "weapon", wrap = "throwable"},
           -- Explosives
        {id = 'WEAPON_PUMPSHOTGUN',name = "Pump Shutgun", desc = "", lvl = "7", thumb = "WEAPON_PUMPSHOTGUN.PNG", rent = "200", buy = "97000", class = "explosives", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_BULLPUPSHOTGUN',name = "BullPup Shotgun", desc = "", lvl = "18", thumb = "WEAPON_BULLPUPSHOTGUN.PNG", rent = "250", buy = "113000", own = "1000", class = "explosives", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_AUTOSHOTGUN',name = "Auto Shotgun", desc = "", lvl = "24", thumb = "WEAPON_AUTOSHOTGUN.PNG", rent = "300", buy = "123000", class = "explosives", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_HEAVYSHOTGUN',name = "Heavy Shotgun", desc = "", lvl = "31", thumb = "WEAPON_HEAVYSHOTGUN.PNG", rent = "325", buy = "150000", class = "explosives", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_PUMPSHOTGUN_MK2',name = "Pump Shotgun Mk2", desc = "", lvl = "50", thumb = "WEAPON_PUMPSHOTGUN_MK2.PNG", rent = "350", buy = "185000", class = "explosives", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_ASSAULTSHOTGUN',name = "Assault Shotgun", desc = "", lvl = "91", thumb = "WEAPON_ASSAULTSHOTGUN.PNG", rent = "550", buy = "240000", class = "explosives", cat = "weapon", wrap = "primary"},
   
        {id = 'WEAPON_FLAREGUN',name = "FlareGun", desc = "", lvl = "7", thumb = "WEAPON_FLAREGUN.PNG", rent = "50", buy = "2500", own = "1000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MINISMG',name = "Mini Smg", desc = "", lvl = "7", thumb = "WEAPON_MINISMG.PNG", rent = "150", buy = "60000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG',name = "Smg", desc = "", lvl = "15", thumb = "WEAPON_SMG.PNG", rent = "200", buy = "75000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MICROSMG',name = "Micro Smg", desc = "", lvl = "22", thumb = "WEAPON_MICROSMG.PNG", rent = "150", buy = "63000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MACHINEPISTOL',name = "Machine Pistol", desc = "", lvl = "30", thumb = "WEAPON_MACHINEPISTOL.PNG", rent = "150", buy = "67000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPDW',name = "Adp", desc = "", lvl = "35", thumb = "WEAPON_COMBATPDW.PNG", rent = "250", buy = "100000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG_MK2',name = "Smg Ak2", desc = "", lvl = "42", thumb = "WEAPON_SMG_MK2.PNG", rent = "250", buy = "120000", class = "explosives", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_ASSAULTSMG',name = "Assault Smg", desc = "", lvl = "48", thumb = "WEAPON_ASSAULTSMG.PNG", rent = "275", buy = "150000", class = "explosives", cat = "weapon", wrap = "secondary"},
   
        {id = 'WEAPON_RPG',name = "Rpg", desc = "", lvl = "22", thumb = "WEAPON_RPG.PNG", rent = "550", class = "explosives", cat = "weapon", wrap = "throwable"},
        {id = 'WEAPON_HOMINGLAUNCHER',name = "Homing Launcher", desc = "", lvl = "35", thumb = "WEAPON_HOMINGLAUNCHER.PNG", rent = "1000", class = "explosives", cat = "weapon", wrap = "throwable"},
        {id = 'WEAPON_GRENADELAUNCHER',name = "Grenade Launcher ", desc = "", lvl = "53", thumb = "WEAPON_GRENADELAUNCHER_SMOKE.PNG", rent = "400", buy = "240000", class = "explosives", cat = "weapon", wrap = "throwable"},
   
        {id = 'WEAPON_GRENADE',name = "Grenade", desc = "", lvl = "1", thumb = "WEAPON_GRENADE.PNG", rent = "175", class = "explosives", cat = "weapon", wrap = "throwable"},
        {id = 'GADGET_PARACHUTE',name = "Parachute", desc = "", lvl = "60", thumb = "WEAPON_PARACHUTE.PNG", rent = "300", buy = "75000", class = "explosives", cat = "weapon", wrap = "throwable"},
   
           -- Marksmamb
        {id = 'WEAPON_MARKSMANRIFLE',name = "Marksmamb Rifle", desc = "", lvl = "35", thumb = "WEAPON_MARKSMANRIFLE.PNG", rent = "6500", class = "marksmamb", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_SNIPERRIFLE',name = "Sniper Rifle", desc = "", lvl = "60", thumb = "WEAPON_SNIPERRIFLE.PNG", rent = "8000", class = "marksmamb", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_MARKSMANRIFLE_MK2',name = "Marksmamb Rifle Mk2", desc = "", lvl = "80", thumb = "WEAPON_MARKSMANRIFLE_MK2.PNG", rent = "8500", class = "marksmamb", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_MUSKET',name = "Musket", desc = "", lvl = "99", thumb = "WEAPON_MUSKET.PNG", rent = "5000", class = "marksmamb", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_HEAVYSNIPER',name = "Heavy Sniper", desc = "", lvl = "120", thumb = "WEAPON_SNIPERRIFLE.PNG", rent = "20000", class = "marksmamb", cat = "weapon", wrap = "primary"},
   
        {id = 'WEAPON_SNSPISTOL',name = "SnS Pistol", desc = "", lvl = "1", thumb = "WEAPON_SNSPISTOL.PNG", rent = "free", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_FLAREGUN',name = "FlareGun", desc = "", lvl = "1", thumb = "WEAPON_FLAREGUN.PNG", rent = "50", buy = "2500", own = "1000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL',name = "Pistol", desc = "", lvl = "1", thumb = "WEAPON_PISTOL.PNG", rent = "150", buy = "20000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPISTOL',name = "Combat Pistol", desc = "", lvl = "6", thumb = "WEAPON_COMBATPISTOL.PNG", rent = "150", buy = "25000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SNSPISTOL_MK2',name = "SnS Pistol Mk2", desc = "", lvl = "11", thumb = "WEAPON_SNSPISTOL_MK2.PNG", rent = "125", buy = "13250", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_HEAVYPISTOL',name = "Heavy Pistol", desc = "", lvl = "20", thumb = "WEAPON_HEAVYPISTOL.PNG", rent = "200", buy = "58000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL50',name = "Pistol 50", desc = "", lvl = "29", thumb = "WEAPON_PISTOL50.PNG", rent = "250", buy = "61000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_APPISTOL',name = "Appistol", desc = "", lvl = "53", thumb = "WEAPON_APPISTOL.PNG", rent = "250", buy = "85000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_DOUBLEACTION',name = "Double Action", desc = "", lvl = "62", thumb = "WEAPON_DOUBLEACTION.PNG", rent = "275", buy = "90000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_REVOLVER',name = "Revolver", desc = "", lvl = "72", thumb = "WEAPON_REVOLVER.PNG", rent = "475", buy = "100000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_REVOLVER_MK2',name = "Revolver Mk2", desc = "", lvl = "97", thumb = "WEAPON_REVOLVER_MK2.PNG", rent = "500", buy = "120000", class = "marksmamb", cat = "weapon", wrap = "secondary"},
   
           -- Medic
        {id = 'WEAPON_PUMPSHOTGUN',name = "Pump Shutgun", desc = "", lvl = "7", thumb = "WEAPON_PUMPSHOTGUN.PNG", rent = "200", buy = "97000", class = "medic", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_BULLPUPSHOTGUN',name = "BullPup Shotgun", desc = "", lvl = "18", thumb = "WEAPON_BULLPUPSHOTGUN.PNG", rent = "250", buy = "113000", own = "1000", class = "medic", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_AUTOSHOTGUN',name = "Auto Shotgun", desc = "", lvl = "24", thumb = "WEAPON_AUTOSHOTGUN.PNG", rent = "300", buy = "123000", class = "medic", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_HEAVYSHOTGUN',name = "Heavy Shotgun", desc = "", lvl = "31", thumb = "WEAPON_HEAVYSHOTGUN.PNG", rent = "325", buy = "150000", class = "medic", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_PUMPSHOTGUN_MK2',name = "Pump Shotgun Mk2", desc = "", lvl = "50", thumb = "WEAPON_PUMPSHOTGUN_MK2.PNG", rent = "350", buy = "185000", class = "medic", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_ASSAULTSHOTGUN',name = "Assault Shotgun", desc = "", lvl = "91", thumb = "WEAPON_ASSAULTSHOTGUN.PNG", rent = "550", buy = "240000", class = "medic", cat = "weapon", wrap = "primary"},
       
        {id = 'WEAPON_SNSPISTOL', name = "SnS Pistol", desc = "", lvl = "1", thumb = "WEAPON_SNSPISTOL.PNG", rent = "free", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_FLAREGUN', name = "FlareGun", desc = "", lvl = "3", thumb = "WEAPON_FLAREGUN.PNG", rent = "50", buy = "2500", own = "1000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL', name = "Pistol", desc = "", lvl = "5", thumb = "WEAPON_PISTOL.PNG", rent = "100", buy = "20000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPISTOL', name = "Combat Pistol", desc = "", lvl = "6", thumb = "WEAPON_COMBATPISTOL.PNG", rent = "150", buy = "25000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SNSPISTOL_MK2', name = "SnS Pistol Mk2", desc = "", lvl = "11", thumb = "WEAPON_SNSPISTOL_MK2.PNG", rent = "125", buy = "32500", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_DBSHOTGUN', name = "Double Barrel Shotgun", desc = "", lvl = "14", thumb = "WEAPON_DBSHOTGUN.PNG", rent = "200", buy = "55000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_HEAVYPISTOL', name = "Heavy Pistol", desc = "", lvl = "20", thumb = "WEAPON_HEAVYPISTOL.PNG", rent = "200", buy = "58000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_PISTOL50', name = "Pistol 50", desc = "", lvl = "29", thumb = "WEAPON_PISTOL50.PNG", rent = "150", buy = "61000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MINISMG',name = "Mini Smg", desc = "", lvl = "7", thumb = "WEAPON_MINISMG.PNG", rent = "150", buy = "60000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG',name = "Smg", desc = "", lvl = "15", thumb = "WEAPON_SMG.PNG", rent = "200", buy = "75000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MICROSMG',name = "Micro Smg", desc = "", lvl = "22", thumb = "WEAPON_MICROSMG.PNG", rent = "150", buy = "63000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MACHINEPISTOL',name = "Machine Pistol", desc = "", lvl = "30", thumb = "WEAPON_MICROSMG.PNG", rent = "150", buy = "67000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPDW',name = "Adp", desc = "", lvl = "35", thumb = "WEAPON_COMBATPDW.PNG", rent = "250", buy = "100000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG_MK2',name = "Smg Ak2", desc = "", lvl = "42", thumb = "WEAPON_SMG_MK2.PNG", rent = "250", buy = "120000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_ASSAULTSMG',name = "Assault Smg", desc = "", lvl = "48", thumb = "WEAPON_ASSAULTSMG.PNG", rent = "275", buy = "150000", class = "medic", cat = "weapon", wrap = "secondary"},
        {id = 'GADGET_PARACHUTE',name = "Parachute", desc = "", lvl = "60", thumb = "WEAPON_PARACHUTE.PNG", rent = "300", buy = "75000", class = "medic", cat = "weapon", wrap = "secondary"},

           -- Support
        {id = 'WEAPON_MG',name = "Mg", desc = "", lvl = "27", thumb = "WEAPON_MG.PNG", rent = "250", buy = "145000", class = "support", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_GUSENBERG',name = "Gusenberg", desc = "", lvl = "43", thumb = "WEAPON_GUSENBERG.PNG", rent = "250", buy = "149000", own = "1000", class = "support", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_COMBATMG',name = "Combat Mg", desc = "", lvl = "50", thumb = "WEAPON_COMBATMG.PNG", rent = "400", buy = "300000", class = "support", cat = "weapon", wrap = "primary"},
        {id = 'WEAPON_COMBATMG_MK2',name = "Combat Mg Mk2", desc = "", lvl = "83", thumb = "WEAPON_COMBATMG_MK2.PNG", rent = "780", buy = "800000", class = "support", cat = "weapon", wrap = "primary"},
   
        {id = 'WEAPON_FLAREGUN',name = "FlareGun", desc = "", lvl = "7", thumb = "WEAPON_FLAREGUN.PNG", rent = "50", buy = "2500", own = "1000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MINISMG',name = "Mini Smg", desc = "", lvl = "7", thumb = "WEAPON_MINISMG.PNG", rent = "250", buy = "60000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG',name = "Smg", desc = "", lvl = "15", thumb = "WEAPON_SMG.PNG", rent = "270", buy = "75000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MICROSMG',name = "Micro Smg", desc = "", lvl = "22", thumb = "WEAPON_MICROSMG.PNG", rent = "250", buy = "63000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_MACHINEPISTOL',name = "Machine Pistol", desc = "", lvl = "30", thumb = "WEAPON_MACHINEPISTOL.PNG", rent = "270", buy = "67000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_COMBATPDW',name = "Adp", desc = "", lvl = "35", thumb = "WEAPON_COMBATPDW.PNG", rent = "300", buy = "100000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_SMG_MK2',name = "Smg Ak2", desc = "", lvl = "42", thumb = "WEAPON_SMG_MK2.PNG", rent = "325", buy = "120000", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'WEAPON_ASSAULTSMG',name = "Assault Smg", desc = "", lvl = "48", thumb = "WEAPON_ASSAULTSMG.PNG", rent = "350", buy = "150000", class = "support", cat = "weapon", wrap = "secondary"},
   
        {id = 'WEAPON_GRENADE',name = "Grenade", desc = "", lvl = "1", thumb = "WEAPON_GRENADE.PNG", rent = "175", class = "support", cat = "weapon", wrap = "secondary"},
        {id = 'GADGET_PARACHUTE',name = "Parachute", desc = "", lvl = "60", thumb = "WEAPON_PARACHUTE.PNG", rent = "300", buy = "75000", class = "support", cat = "weapon", wrap = "secondary"},

        --VEHICULE
        {id = "scorcher",name = "Scorcher", desc = "", lvl =  "0", thumb= "SCORCHER.PNG", rent= "free", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "rancherxl",name = "Rancher", desc = "", lvl =  "0", thumb= "RANCHERXL.PNG", rent= "free", buy = "75000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "rebel",name = "Rebel", desc = "", lvl =  "3", thumb= "REBEL.PNG", rent= "100", buy = "80000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "blazer",name = "Blazer", desc = "", lvl =  "4", thumb= "BLAZER.PNG", rent= "150", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "sanchez2",name = "Sanchez", desc = "", lvl =  "5", thumb= "SANCHEZ2.PNG", rent= "250", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "dune",name = "Dune", desc = "", lvl =  "6", thumb= "DUNE.PNG", rent= "270", buy = "90000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "crusader",name = "Crusader", desc = "", lvl =  "7", thumb= "CRUSADER.PNG", rent= "300", buy = "110000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "m939",name = "M939", desc = "", lvl =  "8", thumb= "M939.PNG", rent= "750", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "policet",name = "Police T", desc = "", lvl =  "10", thumb= "POLICET.PNG", rent= "600", buy = "130000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "rumpo3",name = "Rumpo", desc = "", lvl =  "11", thumb= "RUMPO3.PNG", rent= "700", buy = "140000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "wastelander",name = "Wastelander", desc = "", lvl =  "13", thumb= "WASTELANDER.PNG", rent= "650", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "fbi2",name = "Fbi", desc = "", lvl =  "14", thumb= "FBI2.PNG", rent= "600", buy = "130000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "guardian",name = "Guardian", desc = "", lvl =  "18", thumb= "guardian.PNG", rent= "600", buy = "135000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "dune3",name = "Dune Armed", desc = "", lvl =  "21", thumb= "DUNE3.PNG", rent= "10000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "bf400",name = "Bf 400", desc = "", lvl =  "24", thumb= "BF400.PNG", rent= "300", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "technical3",name = "Technical", desc = "", lvl =  "27", thumb= "TECHNICAL3.PNG", rent= "12000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "insurgent2",name = "Gurkha", desc = "", lvl =  "31", thumb= "GURKHA.PNG", rent= "1250", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "baller5",name = "Baller", desc = "", lvl =  "33", thumb= "BALLER6.PNG", rent= "1500", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "xls2",name = "Xls", desc = "", lvl =  "33", thumb= "XLS2.PNG", rent= "2200", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "cog552",name = "Cog552", desc = "", lvl =  "33", thumb= "COG552.PNG", rent= "2000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "schafter5",name = "Schafter", desc = "", lvl =  "33", thumb= "SCHAFTER5.PNG", rent= "3300", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "unarm",name = "Hummer", desc = "", lvl =  "37", thumb= "UNARM.PNG", rent= "2000", buy = "325000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "barrage",name = "Barrage", desc = "", lvl =  "40", thumb= "BARRAGE.PNG", rent= "22500", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "insurgent",name = "Insurgent3", desc = "", lvl =  "57", thumb= "INSURGENT3.PNG", rent= "45000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "dukes2",name = "Dukes2", desc = "", lvl =  "81", thumb= "DUKES2.PNG", rent= "1000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "scarab",name = "Scarab", desc = "", lvl =  "93", thumb= "SCARAB.PNG", rent= "2000", class= 'Ground', cat= 'vehicule', wrap = "primary"},
        {id = "rhino",name = "Rhino", desc = "", lvl =  "100", thumb= "RHINO.PNG", rent= "200000", class= 'Ground', cat= 'vehicule', wrap = "primary"},

        --AERIEN
        {id = "buzzard2",name = "Buzzard 2", desc = "", lvl =  "15", thumb= "BUZZARD2.PNG", rent= "1250", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "haitun",name = "Haintun", desc = "", lvl =  "25", thumb= "HAITUN.PNG", rent= "2000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "annihilator",name = "Annihilator", desc = "", lvl =  "30", thumb= "ANNIHILATOR.PNG", rent= "3000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "mhx",name = "Mhx", desc = "", lvl =  "35", thumb= "MHX.PNG", rent= "3250", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "buzzard",name = "Buzzard", desc = "", lvl =  "50", thumb= "BUZZARD.PNG", rent= "25500", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "cargobob",name = "Cargobob", desc = "", lvl =  "53", thumb= "CARGOBOB.PNG", rent= "3000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "nh90",name = "NH90", desc = "", lvl =  "60", thumb= "NH90.PNG", rent= "4000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "pavehawk",name = "Pave Hawk", desc = "", lvl =  "63", thumb= "PAVEHAWK.PNG", rent= "28000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "valkyrie2",name = "Valkyrie", desc = "", lvl =  "73", thumb= "VALKYRIE2.PNG", rent= "35500", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "pavelow",name = "Pavelow", desc = "", lvl =  "75", thumb= "PAVELOW.PNG", rent= "3750", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "hunter",name = "Hunter", desc = "", lvl =  "100", thumb= "HUNTER.PNG", rent= "40000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "osprey",name = "Osprey", desc = "", lvl =  "102", thumb= "OSPREY.PNG", rent= "12000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "ahx",name = "AHX", desc = "", lvl =  "105", thumb= "AHX.PNG", rent= "41000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "ah1z",name = "Ah1z", desc = "", lvl =  "110", thumb= "AH1Z.PNG", rent= "42000", class= 'Air', cat= 'vehicule', wrap = "primary"},
        {id = "akula",name = "akula", desc = "", lvl =  "220", thumb= "AH1Z.PNG", rent= "42000", class= 'Air', cat= 'vehicule', wrap = "primary"},
    }
end)

Weapons = {
    ["5748568251"] = GetHashKey("weapon_compactrifle"),
    ["5748568252"] = GetHashKey("weapon_assaultrifle"),
    ["5748568253"] = GetHashKey("weapon_carbinerifle"),
    ["5748568254"] = GetHashKey("weapon_advancedrifle"),
    ["5748568255"] = GetHashKey("weapon_bullpuprifle"),
    ["5748568256"] = GetHashKey("weapon_specialcarbine"),
    ["5748568257"] = GetHashKey("weapon_assaultrifle_mk2"),
    ["5748568258"] = GetHashKey("weapon_carbinerifle_mk2"),
    ["5748568259"] = GetHashKey("weapon_specialcarbine_mk2"),
    ["5748568260"] = GetHashKey("weapon_snspistol"),
    ["5748568261"] = GetHashKey("weapon_flaregun"),
    ["5748568262"] = GetHashKey("weapon_pistol"),
    ["5748568263"] = GetHashKey("weapon_combatpistol"),
    ["5748568264"] = GetHashKey("weapon_snspistol_mk2"),
    ["5748568265"] = GetHashKey("weapon_dbshotgun"),
    ["5748568266"] = GetHashKey("weapon_heavypistol"),
    ["5748568267"] = GetHashKey("weapon_pistol50"),
    ["5748568268"] = GetHashKey("weapon_pistol_mk2"),
    ["5748568269"] = GetHashKey("weapon_appistol"),
    ["5748568270"] = GetHashKey("weapon_revolver"),
    ["5748568271"] = GetHashKey("weapon_revolver_mk2"),
    ["5748568272"] = GetHashKey("weapon_grenade"),
    ["5748568273"] = GetHashKey("weapon_bzgas"),
    ["5748568274"] = GetHashKey("weapon_compactlauncher"),
    ["5748568275"] = GetHashKey("gadget_parachute"),
    ["5748568276"] = GetHashKey("weapon_pumpshotgun"),
    ["5748568277"] = GetHashKey("weapon_bullpupshotgun"),
    ["5748568278"] = GetHashKey("weapon_autoshotgun"),
    ["5748568279"] = GetHashKey("weapon_heavyshotgun"),
    ["5748568280"] = GetHashKey("weapon_pumpshotgun_mk2"),
    ["5748568281"] = GetHashKey("weapon_assaultshotgun"),
    ["5748568282"] = GetHashKey("weapon_minismg"),
    ["5748568283"] = GetHashKey("weapon_smg"),
    ["5748568284"] = GetHashKey("weapon_microsmg"),
    ["5748568285"] = GetHashKey("weapon_machinepistol"),
    ["5748568286"] = GetHashKey("WEAPON_COMBATPDW"),
    ["5748568287"] = GetHashKey("weapon_carbinerifle_mk2"),
    ["5748568288"] = GetHashKey("weapon_assaultsmg"),
    ["5748568289"] = "repairkit",
    ["5748568290"] = GetHashKey("weapon_rpg"),
    ["5748568291"] = GetHashKey("weapon_hominglauncher"),
    ["5748568292"] = GetHashKey("weapon_grenadelauncher"),
    ["5748568293"] = GetHashKey("weapon_grenadelauncher_smoke"),
    ["5748568294"] = GetHashKey("weapon_mg"),
    ["5748568295"] = GetHashKey("weapon_gusenberg"),
    ["5748568296"] = GetHashKey("weapon_combatmg"),
    ["5748568297"] = GetHashKey("weapon_combatmg_mk2"),
    ["5748568298"] = GetHashKey("weapon_marksmanrifle"),
    ["5748568299"] = GetHashKey("weapon_marksmanrifle_mk2"),
    ["5748568100"] = GetHashKey("weapon_sniperrifle"),
    ["5748568101"] = GetHashKey("weapon_musket"),
    ["5748568102"] = GetHashKey("weapon_heavysniper"),
    ["5748568103"] = GetHashKey("weapon_doubleaction"),
    ["5748568104"] = GetHashKey("weapon_heavysniper"),
    ["5748568105"] = GetHashKey("weapon_heavysniper"),
}

